# -*- coding: utf-8 -*-
"""Decision Tree Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BQ385bsWqjtzSU4eIXVItf8HFTi0JSzl

# **Importing the Libraries**
"""

import numpy as np;
import matplotlib.pyplot as plt;
import pandas as pd;

"""# **Importing the dataset**"""

dataset = pd.read_csv("Position_Salaries.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""# **Training the Decision Tree Regression model on the whole dataset**"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X, y)

"""# **Predicting a new result**"""

regressor.predict([[6.5]])

"""# **Visualizing the Decision Tree Regression results(higher resolution)**"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, c="red")
plt.plot(X_grid, regressor.predict(X_grid), color="blue")
plt.title("Truth or Bluff (Desision Tree Regression)")
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()