# -*- coding: utf-8 -*-
"""Random Forest Regression

Automatically generated by Colaboratory.

# **Import the Libraries**
"""

import numpy as np;
import matplotlib.pyplot as plt;
import pandas as pd;

"""# **Import the dataset**"""

dataset = pd.read_csv("Position_Salaries.csv")
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

"""# **Training the Random Forest Regression model on the whole dataset**"""

from sklearn.ensemble import RandomForestRegressor
regressor =  RandomForestRegressor(n_estimators=10, random_state=0)
regressor.fit(X, y)

"""# **Predicitng a new result**"""

regressor.predict([[6.5]])

"""# **Visualizing the Decision Tree Regression results(higher resolution)**"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, c="red")
plt.plot(X_grid, regressor.predict(X_grid), color="blue")
plt.title("Truth or Bluff (Random Forest Regression)")
plt.xlabel('Position Level')
plt.ylabel('Salary')
plt.show()